name: tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # PHP version
    strategy:
      matrix:
        php_version: [5.6]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs composer
      - uses: php-actions/composer@v4
        with:
          composer_version: 1

      # Runs phpunit
      - uses: php-actions/phpunit@v1
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          
      # Runs phpcs
      - name: Execute phpcs
        run: vendor/bin/phpcs -n src
